Made some cmd pages
spo-iitk/docs pull request #2
Opened 2022-12-03 10:27 UTC by ahujatejas06

Made some cmd pages

Logo needs to be edited... just added to check

2022-12-03 19:31 UTC, 1-Harshit requested changes

2022-12-03 19:31 UTC, 1-Harshit commented on docs/overview.md
> +-    RC: 3490
Try nested list

2022-12-03 19:31 UTC, 1-Harshit commented on docs/overview.md
> +The program is divided into multiple sections for the easy management of the different parts. The different sections of the program use separate ports for increased stability. A crash at one of the p
- prefer application
  refer: https://www.geeksforgeeks.org/difference-between-program-and-application/

- Not easy management it is based on microservice arch sorrta neo monolith

2022-12-03 19:31 UTC, 1-Harshit commented on index.md
> +RAS is the new recruitment automation system developed by a team of 10 undergraduate students for the Students' Placement Office, IIT Kanpur to ease-out and automate the internship and placement proc
drop new

2022-12-03 19:31 UTC, 1-Harshit commented on index.md
> +RAS is the new recruitment automation system developed by a team of 10 undergraduate students for the Students' Placement Office, IIT Kanpur to ease-out and automate the internship and placement proc
and what is full form of ras again?

2022-12-03 19:31 UTC, 1-Harshit commented on docs/errors/errors.md
> +This file lists down the various common errors encountered while developing, building and deploying the application.
<3 Noice file Too many stories i've for this

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/cmd.md
> +#### References
nice practice, good

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/cmd.md
> +A mail service is initialized and passed on to the following handlers and the errors are returned to the main function and logged by the logger.
initialized in a goroutine, pls note

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/cmd.md
> +Mail read and write timeouts are defined to 5 seconds and 10 seconds respectively
this timeout is of api calls done to the servals endpoints, emailer works almost instantly

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/cmd.md
> +#### References
nice practice, good

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/cmd.md
> +# main.go
https://github.com/gin-gonic/gin/issues/346

understand and add this somewhere, and put link in refrences

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/auth.md
> +- Recovery (Standard Go middleware) : to recover from any panic
gin middleware

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/auth.md
> +This file defines mail service handler for the authentication service.
come again?

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/auth.md
> +It returns an http server instance of the started server for reading and writing to the mail service.
why this much focus on mailers?

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/auth.md
> +The Go viper package is used to read the [config.yaml secrets file]() and get the port of the authentication service. A new Go engine is initialized and the required middlewares are attached to it.
config yml is part of config directory

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/auth.md
> +Initialized service is passed to [auth router].
and what happens there? put one line of that

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/auth.md
> +- CORS - Cross-Origin Resource Sharing : Custom middleware defined in the middleware documentation
why were these middlewares relevant?

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/admin.md
> +This file defines mail service handler for the admin service.
whaattt

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/admin.md
> +The Go viper package is used to read the [config.yaml secrets file]() and get the port of the various administrator services. A new Go engine is initialized and the required middlewares are attached
and config.yml is not a secret file, didn't get what u meant here

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/admin.md
> +It returns an http server instance of the adminRC server for reading and writing to the mail service.
what is reading and writing to mail service

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/admin.md
> +It returns an http server instance of the adminRC server for reading and writing to the mail service.
what is reading and writing to mail service
it is a channel for crying out loud

2022-12-03 19:31 UTC, 1-Harshit commented on docs/cmd/admin.md
> +### Middlewares Attached to the process
relevance of middleware?

2022-12-03 19:42 UTC, 1-Harshit commented
@ahujatejas06 If the PR name isn't decent will not merge
CC: @abhishekshree

2022-12-04 05:39 UTC, abhishekshree commented on docs/cmd/admin.md
> +This file defines mail service handler for the admin service.
lmao

2022-12-21 20:57 UTC, ahujatejas06 commented on docs/cmd/admin.md
> +The Go viper package is used to read the [config.yaml secrets file]() and get the port of the various administrator services. A new Go engine is initialized and the required middlewares are attached
I meant cinfiguration constants... corrected

2022-12-21 21:01 UTC, ahujatejas06 commented on docs/cmd/auth.md
> +The Go viper package is used to read the [config.yaml secrets file]() and get the port of the authentication service. A new Go engine is initialized and the required middlewares are attached to it.
yeah just added a link to that for reference.

2023-01-16 06:37 UTC, merged